driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: zpool-solaris-11
    driver:
      box: chef/solaris-11.3
  - name: ubuntu-16.04
  - name: freebsd-11.1
suites:
  - name: default
    run_list:
      - recipe[zpool_tester::default]
